server:
  port: 1112

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: eureka-b
  client: # 都为true互相注册
    registerWithEureka:  true
    fetchRegistry: true
    serviceUrl: # 注册到eureka-a上
      defaultZone: http://eureka-a:1111/eureka
