# 集成hystrix
# 比zuul多了限流 ,请求类型限制
# 路径重写
# 动态路由

spring:
  cloud:
    gateway:
      routes:
        - id: wayne_provide
          uri: lb://provide # lb(loadBalanced) 当provide有多个实例 自动负载均衡
          filters: # 局部过滤
            - AddRequestParameter=name,wayne  # 过滤器 请求转发时添加一个参数name值wayne
          predicates: # 断言(以...为根据)
            - Method=GET
#            - Path=/provide-api/** # 效果和下面一样
            - Path=/provide-api/{segment}  # 整个Path路径都会转发到provide 既转发到http://localhost:2223/provide-api/xx 所以404

          # 数组 - 开头
        - id: wayne_route
          uri: http://httpbin.org # 跳转的路径uri
          predicates: # 断言 路径映射(可混合使用)
            - Path=/get # 转发到http://httpbin.org/get
            - Method=GET # 只转发GET请求 POST请求导致404,没代理转发过去
#            - Path=/get/{segment} # 符合/get/**的路径都转发 既转发到http://httpbin.org/get/xxx 所以404
            - Query=name # 请求必须携带name参数 否则不转发 404
            - Query=name,java.* # 请求必须携带name参数,且值必须是java开始否则不转发 404
#            - After=... 哪个时间之后可以调用 Before= ...
      default-filters: # 全局过滤
        - StripPrefix=1 # 去掉请求前缀1个 解决前后端分离的url前缀问题
  #      discovery:
#        locator:
#          enabled: true # 开启自动代理 默认false 不代理其他服务 开启后 如上routes中的映射失效
#          # 代理后的服务名地址要大写!!
  application:
    name: gateway
#  profiles:
#    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug

