server:
  port: 8762

#需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: TEST-CONNECT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/